spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path= /customer/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path= /product/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path= /order/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
